-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.ai_generated_test_cases
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    submission_id uuid NOT NULL,
    input_data text COLLATE pg_catalog."default" NOT NULL,
    expected_output text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    edge_case_type character varying(50) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDING'::character varying,
    actual_output text COLLATE pg_catalog."default",
    stderr text COLLATE pg_catalog."default",
    runtime_ms integer,
    execution_order integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    source character varying(20) COLLATE pg_catalog."default" DEFAULT 'AI'::character varying,
    ai_verified boolean,
    CONSTRAINT ai_generated_test_cases_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ai_reviews
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    submission_id uuid NOT NULL,
    score numeric(5, 2),
    strengths text COLLATE pg_catalog."default",
    weaknesses text COLLATE pg_catalog."default",
    feedback text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    correctness_score numeric(5, 2),
    algorithm_score numeric(5, 2),
    time_complexity character varying(50) COLLATE pg_catalog."default",
    space_complexity character varying(50) COLLATE pg_catalog."default",
    overall_score numeric(5, 2),
    hint text COLLATE pg_catalog."default",
    model_name character varying(100) COLLATE pg_catalog."default" DEFAULT 'qwen2.5-coder:3b'::character varying,
    raw_analysis jsonb,
    reviewed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    execution_mode character varying(20) COLLATE pg_catalog."default",
    analysis_confidence numeric(3, 2),
    analysis_reason text COLLATE pg_catalog."default",
    analysis_entry_point character varying(500) COLLATE pg_catalog."default",
    uses_hardcoded_values boolean DEFAULT false,
    CONSTRAINT ai_reviews_pkey PRIMARY KEY (id),
    CONSTRAINT ai_reviews_submission_id_key UNIQUE (submission_id)
);

CREATE TABLE IF NOT EXISTS public.candidate_profiles
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    github_url text COLLATE pg_catalog."default",
    linkedin_url text COLLATE pg_catalog."default",
    cv_url text COLLATE pg_catalog."default",
    experience_years integer,
    CONSTRAINT candidate_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT candidate_profiles_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.code_executions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    question_id uuid,
    language character varying(50) COLLATE pg_catalog."default" NOT NULL,
    source_code text COLLATE pg_catalog."default" NOT NULL,
    stdin_data text COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    stdout text COLLATE pg_catalog."default",
    stderr text COLLATE pg_catalog."default",
    exit_code integer,
    runtime_ms integer,
    memory_kb integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    completed_at timestamp without time zone,
    CONSTRAINT code_executions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.code_submissions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    interview_candidate_id uuid NOT NULL,
    question_id uuid NOT NULL,
    language character varying(50) COLLATE pg_catalog."default",
    source_code text COLLATE pg_catalog."default" NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'PENDING'::character varying,
    runtime_ms integer,
    memory_kb integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    execution_id uuid,
    candidate_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT code_submissions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coding_questions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    difficulty character varying(20) COLLATE pg_catalog."default",
    created_by uuid NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT coding_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.companies
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    company_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    website text COLLATE pg_catalog."default",
    logo_url text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    created_by uuid,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    CONSTRAINT companies_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.interview_candidates
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    user_id uuid,
    candidate_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    candidate_email character varying(255) COLLATE pg_catalog."default",
    joined_at timestamp without time zone,
    left_at timestamp without time zone,
    CONSTRAINT interview_candidates_pkey PRIMARY KEY (id),
    CONSTRAINT interview_candidates_interview_id_key UNIQUE (interview_id)
);

CREATE TABLE IF NOT EXISTS public.interview_participants
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    user_id uuid NOT NULL,
    participant_role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    joined_at timestamp without time zone,
    left_at timestamp without time zone,
    CONSTRAINT interview_participants_pkey PRIMARY KEY (id),
    CONSTRAINT interview_participants_interview_id_user_id_key UNIQUE (interview_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.interview_participation_log
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    user_id uuid,
    candidate_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    joined_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at timestamp without time zone,
    end_reason character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT interview_participation_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.interview_questions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    question_id uuid NOT NULL,
    question_order integer DEFAULT 0,
    CONSTRAINT interview_questions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.interview_reports
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    content jsonb NOT NULL DEFAULT '{}'::jsonb,
    cv_filename text COLLATE pg_catalog."default",
    cv_markdown text COLLATE pg_catalog."default",
    cv_analysis text COLLATE pg_catalog."default",
    coding_analysis_snapshot text COLLATE pg_catalog."default",
    ai_overall_score numeric(5, 2),
    ai_model character varying(100) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'DRAFT'::character varying,
    generated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by uuid,
    updated_by uuid,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT interview_reports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.interview_sessions
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    host_id uuid,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'WAITING'::character varying,
    started_at timestamp without time zone,
    ended_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT interview_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT interview_sessions_interview_id_key UNIQUE (interview_id)
);

CREATE TABLE IF NOT EXISTS public.interviews
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    meeting_code character varying(50) COLLATE pg_catalog."default" NOT NULL,
    room_password_hash character varying(255) COLLATE pg_catalog."default",
    allow_guest boolean NOT NULL DEFAULT true,
    max_participants integer NOT NULL DEFAULT 10,
    max_interviewers integer NOT NULL DEFAULT 2,
    duration_minutes integer NOT NULL DEFAULT 60,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'SCHEDULED'::character varying,
    scheduled_at timestamp without time zone NOT NULL,
    started_at timestamp without time zone,
    ended_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    active_question_id uuid,
    enable_recording boolean NOT NULL DEFAULT false,
    CONSTRAINT interviews_pkey PRIMARY KEY (id),
    CONSTRAINT interviews_meeting_code_key UNIQUE (meeting_code)
);

CREATE TABLE IF NOT EXISTS public.messages
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    session_id uuid,
    sender_id uuid,
    guest_name character varying(255) COLLATE pg_catalog."default",
    content text COLLATE pg_catalog."default" NOT NULL,
    type character varying(20) COLLATE pg_catalog."default" DEFAULT 'TEXT'::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    meeting_code character varying(50) COLLATE pg_catalog."default",
    sender_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.recordings
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    call_cid character varying(200) COLLATE pg_catalog."default" NOT NULL,
    url text COLLATE pg_catalog."default" NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default",
    duration integer NOT NULL DEFAULT 0,
    recording_type character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    interview_id uuid,
    interview_title character varying(255) COLLATE pg_catalog."default",
    deleted_at timestamp without time zone,
    CONSTRAINT recordings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.recruiter_profiles
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    company_id uuid,
    "position" character varying(100) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    linkedin_url text COLLATE pg_catalog."default",
    cover_image_url text COLLATE pg_catalog."default",
    CONSTRAINT recruiter_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT recruiter_profiles_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.room_presence
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    interview_id uuid NOT NULL,
    user_id uuid NOT NULL,
    participant_role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    session_id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    joined_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT room_presence_pkey PRIMARY KEY (id),
    CONSTRAINT room_presence_interview_id_user_id_session_id_key UNIQUE (interview_id, user_id, session_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    avatar_url text COLLATE pg_catalog."default",
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    provider character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'LOCAL'::character varying,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    last_login_at timestamp without time zone,
    password_changed_at timestamp with time zone NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS public.ai_generated_test_cases
    ADD CONSTRAINT ai_generated_test_cases_submission_id_fkey FOREIGN KEY (submission_id)
    REFERENCES public.code_submissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_ai_generated_test_cases_submission_id
    ON public.ai_generated_test_cases(submission_id);


ALTER TABLE IF EXISTS public.ai_reviews
    ADD CONSTRAINT ai_reviews_submission_id_fkey FOREIGN KEY (submission_id)
    REFERENCES public.code_submissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ai_reviews_submission_id_key
    ON public.ai_reviews(submission_id);


ALTER TABLE IF EXISTS public.candidate_profiles
    ADD CONSTRAINT candidate_profiles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS candidate_profiles_user_id_key
    ON public.candidate_profiles(user_id);


ALTER TABLE IF EXISTS public.code_executions
    ADD CONSTRAINT code_executions_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_code_executions_interview_id
    ON public.code_executions(interview_id);


ALTER TABLE IF EXISTS public.code_executions
    ADD CONSTRAINT code_executions_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.coding_questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_code_executions_question_id
    ON public.code_executions(question_id);


ALTER TABLE IF EXISTS public.code_submissions
    ADD CONSTRAINT code_submissions_execution_id_fkey FOREIGN KEY (execution_id)
    REFERENCES public.code_executions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.code_submissions
    ADD CONSTRAINT code_submissions_interview_candidate_id_fkey FOREIGN KEY (interview_candidate_id)
    REFERENCES public.interview_candidates (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.code_submissions
    ADD CONSTRAINT code_submissions_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.code_submissions
    ADD CONSTRAINT code_submissions_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.coding_questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coding_questions
    ADD CONSTRAINT coding_questions_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.companies
    ADD CONSTRAINT companies_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_companies_created_by
    ON public.companies(created_by);


ALTER TABLE IF EXISTS public.interview_candidates
    ADD CONSTRAINT interview_candidates_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS interview_candidates_interview_id_key
    ON public.interview_candidates(interview_id);


ALTER TABLE IF EXISTS public.interview_candidates
    ADD CONSTRAINT interview_candidates_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.interview_participants
    ADD CONSTRAINT interview_participants_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.interview_participants
    ADD CONSTRAINT interview_participants_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.interview_participation_log
    ADD CONSTRAINT interview_participation_log_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_participation_log_interview
    ON public.interview_participation_log(interview_id);


ALTER TABLE IF EXISTS public.interview_participation_log
    ADD CONSTRAINT interview_participation_log_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.interview_questions
    ADD CONSTRAINT interview_questions_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_interview_questions_interview_id
    ON public.interview_questions(interview_id);


ALTER TABLE IF EXISTS public.interview_questions
    ADD CONSTRAINT interview_questions_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.coding_questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.interview_reports
    ADD CONSTRAINT interview_reports_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.interview_reports
    ADD CONSTRAINT interview_reports_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.interview_reports
    ADD CONSTRAINT interview_reports_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.interview_sessions
    ADD CONSTRAINT interview_sessions_host_id_fkey FOREIGN KEY (host_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.interview_sessions
    ADD CONSTRAINT interview_sessions_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS interview_sessions_interview_id_key
    ON public.interview_sessions(interview_id);


ALTER TABLE IF EXISTS public.interviews
    ADD CONSTRAINT interviews_active_question_id_fkey FOREIGN KEY (active_question_id)
    REFERENCES public.coding_questions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.messages
    ADD CONSTRAINT messages_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.interview_sessions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.recordings
    ADD CONSTRAINT recordings_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_recordings_interview_id
    ON public.recordings(interview_id);


ALTER TABLE IF EXISTS public.recruiter_profiles
    ADD CONSTRAINT recruiter_profiles_company_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.companies (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.recruiter_profiles
    ADD CONSTRAINT recruiter_profiles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS recruiter_profiles_user_id_key
    ON public.recruiter_profiles(user_id);


ALTER TABLE IF EXISTS public.room_presence
    ADD CONSTRAINT room_presence_interview_id_fkey FOREIGN KEY (interview_id)
    REFERENCES public.interviews (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.room_presence
    ADD CONSTRAINT room_presence_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;